### ISSUE TITLE
UUID generator ASL helper class

### ISSUE THREAD

**Issue by aitormoreno** [aslze/asl#1]
[Boost](https://www.boost.org/doc/libs/1_67_0/libs/uuid/doc/uuid.html) provides a [UUID ](https://en.wikipedia.org/wiki/Universally_unique_identifier )generator method

It would be interesting to add a cross platform UUID generator to ASL too.

**Comment by aslze** [comment]
Added a simple UUID version 4 generator.

`Uuid uuid = Uuid::generate();`

that gets an Uuid in its raw binary representation. Usable as a key in a Map.

This convertis it to a String in the usual hex format:

`String uuid = Uuid::generate();`
