### ISSUE TITLE
Can't download GitHub release

### ISSUE THREAD

**Issue by vvanelslande** [aslze/asl#12]
Code:
```cpp
#include <iostream>
#include <asl/Http.h>

int main()
{
    std::cout << asl::Http::get("https://github.com/aslze/asl/releases/download/1.9.3/asl-1.9.3.7z").code() << std::endl;
    return 0;
}
```

Output:
```bash
valentin@pop-os:~/Desktop/notworking$ ./build/notworking 
403
```

Body says `The request signature we calculated does not match the signature you provided`

**Comment by aslze** [comment]
I'll take a look. Github redirects release downloads with a 302 to a different very long URL (should work) but may need to set additional headers...

I just tried curl on that URL and it downloads a redirection HTML page with a link, instead of the content.

**Comment by vvanelslande** [comment]
`curl -L https://github.com/aslze/asl/releases/download/1.9.3/asl-1.9.3.7z -o asl.7z` works

**Comment by aslze** [comment]
OK, yes, I didn't know that flag.

Something with AWS pre-signed URLs... I'll take a look later.

**Comment by vvanelslande** [comment]
fix: remove port in Host header if it's 80 (HTTP) or 443 (HTTPS)

**Comment by aslze** [comment]
I just fixed this. But the commits in your pull requests seemed incomplete. Did they work for you? You checked `url.port != 0` to see if there was no port specified, but a few lines above, that was changed to 80 or 443, so `url.port` would never be zero. I added another variable that checks if there is a port before it is changed.

Thank you!
