### ISSUE TITLE
chars() problem 

### ISSUE THREAD

**Issue by knavels** [aslze/asl#21]
when `String` contains any utf8 characters like an emoji or a character from another language `chars()` works as expected, but when `String` contains only ascii characters, calling `chars()` causes the following error, and it seems it has something related to memory clean up or in the destructor.

```
the error: HEAP CORRUPTION DETECTED: after Normal block (....) at .........
CRT detected that the application wrote to memory after end of heap buffer.
```

```cpp
	asl::String a("a__01");

	auto c = a.chars();
	std::cout << c.length() << std::endl;
	std::cout << a.count() << std::endl;
//	for (int i{0}; i < a.count(); ++i)
//		std::cout << c[i] << std::endl;
        std::getchar();
```

this code for example, this works until pressing a key, and what happens after is just destructing `c` and `a`.
I'm checking this line `int n = utf8toUtf32(str(), c.ptr(), 1);` that I think it might be this.

**Comment by aslze** [comment]
I think it is now fixed. That function writes a null character at the end and there was no space for it.

**Comment by knavels** [comment]
yes it's fixed now, thanks s⭐

**Comment by aslze** [comment]
BTW, in a loop like that it is better to use 

```
for (int i{0}; i < c.length(); ++i)
```

instead of:
```

for (int i{0}; i < a.count(); ++i)
```

because count() has to go through the string every time, but c.length() (the array of code points) is fixed.

**Comment by knavels** [comment]
Definitely, it wasn't the actual code, I was testing to make sure the
count() also is correct.
Thanks anyway 🙏
