### ISSUE TITLE
HTTPS support is broken

### ISSUE THREAD

**Issue by valentinvanelslande** [aslze/asl#3]
GET to `https://httpbin.org/get` -> doesn't work
GET to `http://devkitpro.org/misc/httpexample_rawimg.rgb` -> works
GET to `https://devkitpro.org/misc/httpexample_rawimg.rgb` -> doesn't work
GET to `https://avatars2.githubusercontent.com/u/22228082?s=88&v=4` -> works
POST to `http://httpbin.org/post` -> works
POST to `https://httpbin.org/post` -> doesn't work
I'll use your library in my Citra fork, but due to this issue, a lot of programs using HTTP will not work.

**Comment by aslze** [comment]
I think I have fixed this. Tested on Windows and Linux, all the above GETs work (the POST should too).

It was related to the way I used mbedTLS when setting up TLS handshakes. Seems some severs or protocols needed this change. Explanation: my sockets, when connecting to a host by name, first look up the name in DNS, and then try the found IPs until one connects. In TLS that seems to be not enough: you can't just connect to an IP but you have to also supply the host name so it can be verified (or something like that).

Can you please check if it works for you?

Anyway, there are thinks that will not be supported in the near future, like HTTP/2 or TLS 1.3 (until mbedTLS supports it).

**Comment by valentinvanelslande** [comment]
it's fixed, thanks!
