### ISSUE TITLE
A lot of C2445 errors with Visual Studio 2017

### ISSUE THREAD

**Issue by valentinvanelslande** [aslze/asl#8]

**Comment by aslze** [comment]
What do you mean? I just tried VS 2017 (community) and it compiled without errors or warnings. Besides, I can't find information about such error C2445. There is documentation about C2444 and C2446 though.

**Comment by valentinvanelslande** [comment]
the fix is to change `"x"` in some functions to `asl::String("x")`

**Comment by valentinvanelslande** [comment]
search `C2445 visual studio` and the first result has information about the error.

**Comment by aslze** [comment]
Got it. Done.
